### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by d29553883**
老師我要交作業
我是林正偉
http://54.173.35.252:3000/
http://54.173.35.252:3000/attraction/5

### CODE REVIEW

**Comment by cwpeng** [comment]
input and button border should align with design.

**Comment by d29553883** [comment]
老師請問是指線太粗嗎

**Comment by cwpeng** [comment]
You can check design carefully, maybe border width and style.

**Comment by d29553883** [comment]
老師我修正完了

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
