### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by d29553883**
我是林正偉
http://54.173.35.252:3000/api/attractions?page=0

http://54.173.35.252:3000/api/attractions?page=1&keyword=新北投溫泉區

http://54.173.35.252:3000/api/attraction/49

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
In keyword search, we should response attractions where name contains keyword, not only exactly the same one. So, if we search 館 as keyword, http://54.173.35.252:3000/api/attractions?page=0&keyword=%E9%A4%A8 and http://54.173.35.252:3000/api/attractions?page=1&keyword=%E9%A4%A8 should have something there.

Fix issue and request me review again.

**Comment by d29553883** [comment]
修正完了
我是林正偉
http://54.173.35.252:3000/api/attractions?page=0

http://54.173.35.252:3000/api/attractions?page=1&keyword=溫泉

http://54.173.35.252:3000/api/attraction/49

**Comment by cwpeng** [comment]
http://54.173.35.252:3000/api/attractions?page=0&keyword=%E9%A4%A8 should response page 0 data, http://54.173.35.252:3000/api/attractions?page=1&keyword=%E9%A4%A8 should response page 1 data. But what I get from these two URLs is totally the same. And there are only two pages, no more if we search for 館, search results of different keyword has different max page.

Fix issue, re-request me review from right side in this page.

**Comment by d29553883** [comment]
老師我修正完了
http://54.173.35.252:3000/api/attractions?page=0

http://54.173.35.252:3000/api/attractions?page=1&keyword=館

http://54.173.35.252:3000/api/attraction/49

**Comment by cwpeng** [comment]
Your server is broken for now.

**Comment by d29553883** [comment]
伺服器重啟了

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
