### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by d29553883**
老師我要交作業
我是林正偉
http://54.173.35.252:3000/
http://54.173.35.252:3000/attraction/6

### CODE REVIEW

**Comment by cwpeng** [comment]
Your API is crash for now.

**Comment by d29553883** [comment]
老師我重啟伺服器了

**Comment by cwpeng** [comment]
It's too bad to be accepted in middle size devices.

未命名-3

**Comment by d29553883** [comment]
老師我修正完了

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
